// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKzFOMOp-btEV6cJ53c8PKCaxPG6jyt0',
    appId: '1:170012642686:android:48d191b905bf1982e2f72f',
    messagingSenderId: '170012642686',
    projectId: 'ecomstore-4f2e5',
    storageBucket: 'ecomstore-4f2e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkP7kw7Uj_HPQd0d4lGZhj8ZOv1nBP0HE',
    appId: '1:170012642686:ios:9749d20ad830cdf4e2f72f',
    messagingSenderId: '170012642686',
    projectId: 'ecomstore-4f2e5',
    storageBucket: 'ecomstore-4f2e5.appspot.com',
    iosClientId: '170012642686-5g31f0tdkmr12o1596inair868h0k7u3.apps.googleusercontent.com',
    iosBundleId: 'ch.heiafr.tic.ecomstore',
  );
}
